server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webalyt
    username: root
    password: ahojsvete
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: plugin-click
  cloud:
    config:
      uri: http://localhost:8888
      name: ${spring.application.name}, database, discovery-client, kafka

webalyt:
  serviceType: plugin
  kafkaTopic: cp
  objectId: cp


