server:
  port: 0

spring:
  application:
    name: plugin-resize-recorder
  cloud:
    config:
      uri: http://localhost:8888
      name: ${spring.application.name}, database, discovery-client, kafka

webalyt:
  serviceType: plugin
  kafkaTopic: resize-recorder
  objectId: resize-recorder


