server:
  port: 8888

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      name: ${spring.application.name}
      server:
        git:
          uri: /home/pfilip/Projekty/School/PHD/webalyt-configuration-repository
        bootstrap: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8989/eureka/

management:
  security:
    enabled: false