server:
  port: 8082

spring:
  application:
    name: analytics-web
  cloud:
    config:
      uri: http://localhost:8888
      name: ${spring.application.name}, database, discovery-client, kafka

webalyt:
  serviceType: core
  kafkaTopic: analytics-web
  objectId: analytics-web


