server:
  port: 8989


spring:
  application:
    name: service-manager
  cloud:
    config:
      uri: http://localhost:8888
      name: ${spring.application.name}, discovery-client


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0


