server:
  port: 0

spring:
  application:
    name: plugin-scroll-tracker
  cloud:
    config:
      uri: http://localhost:8888
      name: ${spring.application.name}, database, discovery-client, kafka

webalyt:
  serviceType: plugin
  kafkaTopic: scroll-tracker
  objectId: scroll-tracker


