server:
  port: 8081

spring:
  freemarker:
    cache: false
  application:
    name: analytics-session-player
  cloud:
    config:
      uri: http://localhost:8888
      name: ${spring.application.name}, database, discovery-client, kafka

webalyt:
  serviceType: analytics
  kafkaTopic: session-player
  objectId: session-player


