server:
  port: 0

spring:
  application:
    name: base-etl-processor
  cloud:
    config:
      uri: http://localhost:8888
      name: ${spring.application.name}, database, discovery-client, kafka


management:
  security:
    enabled: false



