server:
  port: 0

spring:
  application:
    name: plugin-loading-performance-info
  cloud:
    config:
      uri: http://localhost:8888
      name: ${spring.application.name}, database, discovery-client, kafka

webalyt:
  serviceType: plugin
  kafkaTopic: lpi
  objectId: lpi


